Repository integr8ly/heimdall, pull requests merged in 2020-01, with the labels that each got.

#18 add vendor fix and check
  Makefile
Labels: approved, lgtm, size/XS

#23 add prow e2e make target
  Makefile
Labels: approved, lgtm, size/XS

#25 default recheck time every 24 hours
  pkg/domain/types.go
Labels: approved, lgtm, size/XS

#26 fix error on namespace on service creation
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#27 remove TODO
  pkg/controller/imagemonitor/controller.go
Labels: approved, lgtm, size/XS

#20 Intly 4637 add heimdall e2e test
  Makefile
  test/e2e/heimdall_test.go
Labels: approved, lgtm, size/L

#29 fix issue where non version tags failed
  cmd/cli/main.go
  pkg/cluster/images.go
  pkg/registry/images.go
  pkg/registry/images_test.go
  pkg/rhcc/service.go
Labels: approved, lgtm, size/M
